# Generated by Django 5.1.3 on 2025-02-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='required_fields_offer',
            field=models.JSONField(default=dict),
        ),
    ]
