# Generated by Django 5.1.3 on 2025-02-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0002_client_required_fields_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='required_fields_offer',
        ),
        migrations.AddField(
            model_name='product',
            name='required_fields_offer',
            field=models.JSONField(default=dict),
        ),
    ]
