# Generated by Django 5.1.3 on 2025-02-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0003_remove_client_required_fields_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contract_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wartość umowy'),
        ),
        migrations.AddField(
            model_name='client',
            name='final_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_by_client', to='CrmModuleOne.offer', verbose_name='Finalna oferta'),
        ),
        migrations.AddField(
            model_name='client',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Marża'),
        ),
        migrations.AddField(
            model_name='offer',
            name='total_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Całkowita marża'),
        ),
    ]
