# Generated by Django 5.1.3 on 2025-02-28 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0004_client_contract_value_client_final_offer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prelead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Imię może zawierać tylko litery.')], verbose_name='Imię')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s-]+$', "Numer telefonu może zawierać tylko cyfry, spacje, myślniki i opcjonalny znak '+'.")], verbose_name='Telefon')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Miejscowość')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kod pocztowy')),
            ],
        ),
    ]
