# Generated by Django 5.1.3 on 2025-05-12 10:12

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0005_prelead'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelead',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prelead',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ\\s-]+$', 'Nazwisko może zawierać tylko litery.')], verbose_name='Nazwisko'),
        ),
        migrations.AddField(
            model_name='prelead',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notatka'),
        ),
        migrations.AddField(
            model_name='prelead',
            name='potential',
            field=models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki'), ('very_high', 'Bardzo wysoki')], default='medium', max_length=10, verbose_name='Potencjał'),
        ),
        migrations.AlterField(
            model_name='prelead',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-zżźćńółęąśŻŹĆĄŚĘŁÓŃ\\s-]+$', 'Imię może zawierać tylko litery.')], verbose_name='Imię'),
        ),
    ]
