# Generated by Django 5.1.3 on 2025-05-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0006_prelead_created_at_prelead_last_name_prelead_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
