# Generated by Django 5.1.3 on 2025-05-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0008_prelead_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelead',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
