# Generated by Django 5.1.3 on 2025-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0009_alter_prelead_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelead',
            name='status',
            field=models.CharField(choices=[('ST', 'ST'), ('NO1', 'NO1'), ('NO2', 'NO2'), ('NO3', 'NO3'), ('NN', 'NN'), ('NN2', 'NN2'), ('NUM', 'NUM'), ('UM', 'UM')], default='ST', max_length=4, verbose_name='Status'),
        ),
    ]
