# Generated by Django 5.1.3 on 2025-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0011_alter_prelead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelead',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
