# Generated by Django 5.1.3 on 2025-05-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0012_prelead_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelead',
            name='status',
            field=models.CharField(blank=True, choices=[('ST', 'ST'), ('NO1', 'NO1'), ('NO2', 'NO2'), ('NO3', 'NO3'), ('NN', 'NN'), ('NN2', 'NN2'), ('NUM', 'NUM'), ('UM', 'UM'), ('PR', 'PR')], max_length=4, null=True, verbose_name='Status'),
        ),
    ]
