# Generated by Django 5.1.3 on 2025-05-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0013_alter_prelead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prelead',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notatka'),
        ),
    ]
