# Generated by Django 5.1.3 on 2025-05-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0014_alter_prelead_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('precinct', models.CharField(max_length=100)),
                ('plot_number', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prelead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='CrmModuleOne.prelead')),
            ],
        ),
    ]
