# Generated by Django 5.1.3 on 2025-05-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0015_parcel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='prelead',
            new_name='lead',
        ),
    ]
