# Generated by Django 5.1.3 on 2025-05-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrmModuleOne', '0016_rename_prelead_parcel_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
